version: '3.7'
services:
  dev:
    container_name: crawler
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh"]
    volumes:
      - .:/app
    stdin_open: true
    tty: true
